src/Entity/Club.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClubRepository")
 */
class Club
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $acronym;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region", inversedBy="clubs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $region;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Affiliate", mappedBy="club")
     */
    private $members;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tournament", mappedBy="organizer")
     */
    private $tournaments;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Archer")
     */
    private $owner;

    public function __construct()
    {
        $this->members = new ArrayCollection();
        $this->tournaments = new ArrayCollection();
    }

    public function __ToString()
    {
        return $this->getFullname() ;
    }

    public function getFullname()
    {
        return $this->getAcronym() . ' - ' . $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getAcronym(): ?string
    {
        return $this->acronym;
    }

    public function setAcronym(string $acronym): self
    {
        $this->acronym = $acronym;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @return Collection|Affiliate[]
     */
    public function getMembers(): Collection
    {
        return $this->members;
    }

    /**
     * @return Collection|Affiliate[]
     */
    public function getMembersActif(): Collection
    {
        return $this->members->filter(function(Affiliate $affiliate) {
            return $affiliate->getAffiliateEnd() == null;
        }); 
    }

    /**
     * @return Collection|Affiliate[]
     */
    public function getMembersInactif(): Collection
    {
        return $this->members->filter(
            function(Affiliate $affiliate) {
                return $affiliate->getAffiliateEnd() != null;
            }
        ); 
    }

    public function addMember(Affiliate $member): self
    {
        if (!$this->members->contains($member)) {
            $this->members[] = $member;
            $member->setClub($this);
        }
        return $this;
    }

    public function removeMember(Affiliate $member): self
    {
        if ($this->members->contains($member)) {
            $this->members->removeElement($member);
            // set the owning side to null (unless already changed)
            if ($member->getClub() === $this) {
                $member->setClub(null);
            }
        }
        return $this;
    }

    /**
     * @return Collection|Tournament[]
     */
    public function getTournaments(): Collection
    {
        return $this->tournaments;
    }

    public function addTournament(Tournament $tournament): self
    {
        if (!$this->tournaments->contains($tournament)) {
            $this->tournaments[] = $tournament;
            $tournament->setOrganizer($this);
        }

        return $this;
    }

    public function removeTournament(Tournament $tournament): self
    {
        if ($this->tournaments->contains($tournament)) {
            $this->tournaments->removeElement($tournament);
            // set the owning side to null (unless already changed)
            if ($tournament->getOrganizer() === $this) {
                $tournament->setOrganizer(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?Archer
    {
        return $this->owner;
    }

    public function setOwner(?Archer $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Form/PelotonType.php
<?php

namespace App\Form;

use App\Type\DateTimeType;
use App\Entity\Peloton;
use App\Entity\Tournament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class PelotonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $tournament = $options['tournament'];

        $builder
            ->add('maxParticipant', IntegerType::class, [
                'label' => 'peloton.max_participant'
            ])
            ->add('type', ChoiceType::class, array(
                'required' => true,
                'label' => 'peloton.type',
                'placeholder' => 'peloton.type_placeholder',
                'choices'  => Peloton::getTypeList(),
                'choice_label' => function ($value, $key, $index) {
                    return $value;
                }))
            ->add('startTime', DateTimeType::class, [
                'required' => true, 
                'label' => 'peloton.start_time', 
                'widget' => 'single_text'
                // 'min'
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Peloton::class,
            'csrf_token_id' => 'peloton',
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            'translation_domain' => 'forms',
            'tournament'  => Tournament::class,
        ]);
    }
}

src/Controller/PelotonController.php
<?php

namespace App\Controller;

use App\Entity\Peloton;
use App\Form\PelotonType;
use App\Entity\Tournament;
use App\Entity\Participant;
use App\Form\ParticipantType;
use App\Repository\ParticipantRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Service\ParticipationHelper;

/**
 * @Route("/tournament/{id_tournament}-{slug}/peloton")
 */
class PelotonController extends AbstractController
{
    /**
     * @Route("/new", name="peloton_new", methods={"GET","POST"}) 
     */
    public function new(Request $request, Tournament $tournament): Response
    {
        $peloton = new Peloton();
        $peloton->setStartTime($tournament->getStartDate());
        dump($peloton);
        $form = $this->createForm(PelotonType::class, $peloton, ['tournament' => $tournament]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            
            $peloton->setTournament($tournament);
            $entityManager->persist($peloton);
            $entityManager->flush();

            $this->addFlash('success', 'Création d\'un nouveau peloton pour la compétition');

            return $this->redirectToRoute('tournament_show', ['id' => $tournament->getId(), 'slug' => $tournament->getSlug()]);
        }

        return $this->render('peloton/new.html.twig', [
            'tournament' => $tournament,
            'peloton' => $peloton,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="peloton_show", methods={"GET"})
     */
    public function show(Peloton $peloton, ParticipationHelper $helper): Response
    {
        $user = $this->getUser();
        return $this->render('peloton/show.html.twig', [
            'peloton' => $peloton,
            'isAlreadyRegistered' => $user == null ? false : $helper->isAlreadyRegistered($user->getArcher(), $peloton)            
        ]);
    }

    /**
     * @Route("/{id}/edit", name="peloton_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Peloton $peloton): Response
    {
        $form = $this->createForm(PelotonType::class, $peloton);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('peloton_show', ['id_tournament' => $peloton->getTournament()->getId(),
                                                            'slug' => $peloton->getTournament()->getSlug(), 
                                                            'id' => $peloton->getId()]);
        }

        return $this->render('peloton/edit.html.twig', [
            'peloton' => $peloton,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="peloton_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tournament $tournament, Peloton $peloton): Response
    {
        if ($this->isCsrfTokenValid('delete'.$peloton->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($peloton);
            $entityManager->flush();
            
            $this->addFlash('success', 'Le peloton a bien été supprimé');
        }

        return $this->redirectToRoute('tournament_show', ['id' => $tournament->getId(), 'slug' => $tournament->getSlug()]);
    }

    /**
     * @Route("/{id}/register", name="peloton_register", methods="GET|POST")
     */
    public function register(Request $request, Peloton $peloton, ParticipationHelper $helper): Response
    {
        if($helper->isAlreadyRegistered($this->getUser()->getArcher(), $peloton))
        {
            $this->addFlash('warning', 'Vous êtes déjà inscrit à ce peloton');
            return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
        }

        $participant = new Participant();
        $participant->setPeloton($peloton);
        $participant->setArcher($this->getUser()->getArcher());
        $participant->setCategory($this->getUser()->getArcher()->getDefaultCategory());
        $form = $this->createForm(ParticipantType::class, $participant, ['user' => $this->getUser()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) { 
            $em = $this->getDoctrine()->getManager();
            $em->persist($participant);
            $em->flush();

            $this->addFlash('success', 'Vous avez été inscrit à ce peloton');

            return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
        }        

        return $this->render('participant/register.html.twig', [
            'participant' => $participant,
            'peloton' => $peloton,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/unregister", name="peloton_unregister", methods="GET|POST")
     */
    public function unregister(Request $request, Peloton $peloton, ParticipationHelper $helper): Response
    {
        if(!$helper->isAlreadyRegistered($this->getUser()->getArcher(), $peloton))
        {
            $this->addFlash('warning', 'Vous ne pouvez pas vous désincrire à un peloton auquel vous n\'êtes pas déjà inscrit');
            return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
        }

        $helper->cancelParticipation($this->getUser()->getArcher(), $peloton);
        $this->addFlash('success', 'Vous avez bien été désinscrit du peloton');

        return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
    }

    /**
     * @Route("/{id}/registerAnother", name="peloton_register_another", methods="GET|POST")
     */
    public function registerAnother(Request $request, Peloton $peloton, ParticipationHelper $helper): Response
    {
        if($helper->isAlreadyRegistered($this->getUser()->getArcher(), $peloton))
        {
            return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
        }

        $participant = new Participant();
        $participant->setPeloton($peloton);
        $participant->setArcher($this->getUser()->getArcher());
        $participant->setCategory($this->getUser()->getArcher()->getDefaultCategory());
        $form = $this->createForm(ParticipantType::class, $participant, ['user' => $this->getUser()
                                                                        , 'disabled_archer' => !in_array('ROLE_ADMIN', $this->getUser()->getRoles())
                                                                        ]);
                                                                        // , 'is_already_registered' => $participantRepository->isAlreadyRegistered($participant)]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) { 
            // TODO : message à améliorer => Vous avez été inscrit au Peloton Ou si admin, le nom de la personne inscrite
            // if($value)
            // {
            //     $this->addFlash('warning', '"' . $participant->getArcher()->getFullname() . '" est déjà inscrit à ce peloton');
            // }
            // else
            // {
                $em = $this->getDoctrine()->getManager();
                $em->persist($participant);
                $em->flush();

                $this->addFlash('success', '"' . $participant->getArcher()->getFullname() . '" a été inscrit à ce peloton');
            // }

            return $this->redirectToRoute('tournament_show', ['id' => $peloton->getTournament()->getId(), 'slug' => $peloton->getTournament()->getSlug()]);
        }        

        return $this->render('participant/register.html.twig', [
            'participant' => $participant,
            'peloton' => $peloton,
            'form' => $form->createView(),
        ]);
    }
}

templates/peloton/_delete_form.html.twig
<form method="post" action="{{ path('peloton_delete', {'id_tournament': peloton.tournament.id, 'slug' : peloton.tournament.slug, 'id': peloton.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ peloton.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/peloton/edit.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}Edit Peloton{% endblock %}

{% block body %}
    <h1>Edit Peloton</h1>

    {{ include('peloton/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('peloton_show', {'id_tournament': peloton.tournament.id, 'slug' : peloton.tournament.slug , 'id': peloton.id }) }}">{% trans %}common.back_list{% endtrans %}</a>

    {{ include('peloton/_delete_form.html.twig') }}
{% endblock %}

templates/peloton/index.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}Peloton index{% endblock %}

{% block body %}
    <h1>Peloton index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>MaxParticipant</th>
                <th>Type</th>
                <th>StartTime</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for peloton in pelotons %}
            <tr>
                <td>{{ peloton.id }}</td>
                <td>{{ peloton.maxParticipant }}</td>
                <td>{{ peloton.type }}</td>
                <td>{{ peloton.startTime ? peloton.startTime|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('peloton_show', {'id': peloton.id}) }}">show</a>
                    <a href="{{ path('peloton_edit', {'id': peloton.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('peloton_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/peloton/new.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}New Peloton{% endblock %}

{% block body %}
    <h1>{% trans %}peloton.add{% endtrans %}</h1>

    {{ include('peloton/_form.html.twig') }}

    <a href="{{ path('tournament_show', {'id': tournament.id, 'slug': tournament.slug}) }}" class="btn btn-light"><i class="fad fa-chevron-left"></i> {% trans %}common.back_list{% endtrans %}</a>
{% endblock %}

templates/peloton/show.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}Peloton{% endblock %}

{% block body %}
    <h1>Peloton</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Max Participant</th>
                <td>{{ peloton.maxParticipant }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ peloton.type }}</td>
            </tr>
            <tr>
                <th>Start Time</th>
                <td>{{ peloton.startTime ? peloton.startTime|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
       <thead>
            <tr>
                <th>Club</th>
                <th>Full Name</th>
                <th>Total</th>
                <th>10</th>
                <th>9</th>
                {% if is_granted('ROLE_ADMIN') %}
                <th>Action<th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
        {% for participant in peloton.participants %}
            <tr>
            {% set foo = participant.archer.affiliations|reverse|first %}
                <td>{{ foo.club.acronym }}</td>
                <td>{{ participant.archer.fullname }}</td>
                <td>{{ participant.points }}</td>
                <td>{{ participant.numberoften }}</td>
                <td>{{ participant.numberofnine }}</td>
                {% if is_granted('ROLE_ADMIN') %}
                <td>
                    <a href="{{ path('participant_edit', {'slug' : peloton.tournament.slug, 'id': participant.id}) }}"><i class="fad fa-money-check-edit"></i></a>
                    {# <a href="{{ path('participant_edit', {'slug' : peloton.tournament.slug, 'id': participant.id}) }}"><i class="fad fa-user-times"></i></a> #}
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <div class="btn btn-group">
        <a href="{{ path('tournament_show', {'id': peloton.tournament.id, 'slug': peloton.tournament.slug}) }}" class="btn btn-light"><i class="fad fa-chevron-left"></i> {% trans %}common.back_list{% endtrans %}</a>
        {% if (is_granted('ROLE_ARCHER') and date(peloton.starttime) > date("now")) 
                or is_granted('ROLE_ADMIN') %}
            {# Si je suis déjà inscrit, il faut prévoir une désinscription de l'archer,
                mais d'où pourrai provenir l'information comme quoi la personne est déjà inscrite ?
                
                Quid de l'admin
            #}
            {% if not isAlreadyRegistered %}
            <a href="{{ path('peloton_register', {'id_tournament': peloton.tournament.id, 'slug': peloton.tournament.slug, 'id' : peloton.id}) }}"  class="btn btn-success">S'inscrire</a>
            {% else %}
            <a href="{{ path('peloton_unregister', {'id_tournament': peloton.tournament.id, 'slug': peloton.tournament.slug, 'id' : peloton.id}) }}"  class="btn btn-warning">Se désinscrire</a>
            {% endif %}
        {% endif %}
    
    
        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('peloton_edit', {'id_tournament': peloton.tournament.id, 'slug' : peloton.tournament.slug, 'id': peloton.id}) }}" class="btn btn-primary">edit</a>

            {{ include('peloton/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}